In [12]:
import numpy as np

create a 1-d array

In [13]:
list1 = [2,4,6,8]
array1 = np.array(list1)

In [14]:
array2 = np.array([1,2,3,4,5])
print(array2)

[1 2 3 4 5]


creating a 2-d Array


In [15]:
array3 = np.array([[1,2,3,4,5],
                  [6,7,8,9,10]])
print(array3)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [16]:
array4 = np.array([[[1,2,3,4,5],
                    [6,7,8,9,10],
                    [2,4,6,8,10]],

                  [[11,22,34,45,56],
                   [67,78,89,90,10],
                   [25,544,63,82,91]]])
print(array4)

[[[  1   2   3   4   5]
  [  6   7   8   9  10]
  [  2   4   6   8  10]]

 [[ 11  22  34  45  56]
  [ 67  78  89  90  10]
  [ 25 544  63  82  91]]]


In [8]:
array5 = np.array([2,4,6])
print(array5.dtype)

int64


In [9]:
array6 = np.array([[[1,2,3,4,5],
                    [6,7,8,9,10],
                    [2,4,6,8,10]],

                  [[11,22,34,45,56],
                   [67,78,89,90,10],
                   [25,544,63,82,91]]])
print(array6)
print(array6.dtype)
print(array6.ndim)
print(array6.size)
print(array6.shape)






[[[  1   2   3   4   5]
  [  6   7   8   9  10]
  [  2   4   6   8  10]]

 [[ 11  22  34  45  56]
  [ 67  78  89  90  10]
  [ 25 544  63  82  91]]]
int64
3
30
(2, 3, 5)


attribute size

In [10]:
array7 = np.array([7,14,21,28,35])
array8 = np.array([1,2,3,4,5], dtype=np.int32)
print(array7.itemsize)
print(array8.itemsize)

8
4


Compute mean using numpy

In [11]:


marks = np.array([82,84,78,96,99])
mean_marks=np.mean(marks)
print(mean_marks)

87.8


Standard deviation of numpy array

In [17]:
marks = np.array([82,84,78,96,99])
std_marks=np.std(marks)
print(std_marks)


8.207313811473277


Median using numpy

In [18]:
marks = np.array([82,84,78,96,99])
median_marks=np.median(marks)
print(median_marks)


84.0


Numpy Percentile


In [19]:
marks =np.array([82,84,96,78,100])
percentile_marks=np.percentile(marks,75)
print(percentile_marks)

96.0


Numpy max


In [20]:
marks = np.array([82,84,78,96,99])
max_marks=np.max(marks)
print(max_marks)

99


Numpy min


In [21]:
marks = np.array([82,84,78,96,99])
min_marks=np.min(marks)
print(min_marks)

78


nbytes

In [22]:
array9 = np.array([2,4,6,8])
print(array9.nbytes)

32
